apiVersion: apps/v1
kind: Deployment
metadata:
  name: sessions-deployment
  labels:
    app: sessions-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sessions
  template:
    metadata:
      name: sessions
      labels:
        app: sessions
        app.kubernetes.io/name: sessions
    spec:
      containers:
        - name: sessions-deployment
          image: jejikeh/versity.sessions
          ports:
            - containerPort: 443
              name: https-web-api
            - containerPort: 80
              name: http-web-api
          env:
            - name: ASPNETCORE_URLS
              value: http://+80;
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health-check
              port: 80
          readinessProbe:
            httpGet:
              path: /health-check
              port: 80
          volumeMounts:
            - mountPath: /app/appsettings.Production.json
              subPath: appsettings.Production.json
              name: versity-sessions-secret-appsettings
      restartPolicy: Always
      volumes:
        - name: versity-sessions-secret-appsettings
          secret:
            secretName: versity-sessions-secret-appsettings