apiVersion: v1
kind: Service
metadata:
  name: sessions-service
spec:
  selector:
    app.kubernetes.io/name: sessions
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
