apiVersion: v1
kind: Service
metadata:
  name: sessions-redis-service
spec:
  selector:
    app: sessions-redis
    app.kubernetes.io/name: sessions-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP