version: '3.1'

services:
  elasticsearch:
    container_name: els
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - dev

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.8.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - dev

  versity-products-db:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=versity_products_dev
      - POSTGRES_USER=versity_dev
      - POSTGRES_PASSWORD=versity_dev
    ports:
      - 5432
    volumes:
      - postgres-data:/data/db
    networks:
      - dev
  
  versity-products-service:
    image: jejikeh/versity.products:latest
    container_name: versity-products-service
    depends_on:
      - versity-products-db
    ports:
      - 80
      - 443
    build:
      context: .
      dockerfile: src/Versity.Products/Dockerfile
    environment:
      - ConnectionString=Host=versity-products-db;Port=5432;Username=versity_dev;Password=versity_dev;Database=versity_products_dev;
      - ASPNETCORE_ENVIRONMENT=DEVELOPMENT
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=versity
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
      - JWT__Key=06AA645D-B70D-446F-90D7-192A5C1CAA6A
      - JWT__Issuer=https://versity.users:4001
      - JWT__Audience=https://versity.users:4001
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/AppData/Roaming/Microsoft/UserSecrets/:/root/.microsoft/usersecrets:ro
    networks:
      - dev

  versity-users-db:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=versity_users_dev
      - POSTGRES_USER=versity_dev
      - POSTGRES_PASSWORD=versity_dev
    ports:
      - 5432
    volumes:
      - postgres-data:/data/db
    networks:
      - dev

  versity-users-service:
    image: jejikeh/versity.users:latest
    container_name: versity-users-service
    depends_on:
      - versity-users-db
    ports:
      - 80
      - 443
    build:
      context: .
      dockerfile: src/Versity.Users/Dockerfile
    environment:
      - ConnectionString=Host=versity-users-db;Port=5432;Username=versity_dev;Password=versity_dev;Database=versity_users_dev;
      - Mailgun__Private__ApiKey=43304ec0eca931e64b1adee47aaab749-135a8d32-174884e4
      - ASPNETCORE_ENVIRONMENT=DEVELOPMENT
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=versity
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
      - JWT__Key=06AA645D-B70D-446F-90D7-192A5C1CAA6A
      - JWT__Issuer=https://versity.users:4001
      - JWT__Audience=https://versity.users:4001
      - EMAIL__From=versity.identity.dev@gmail.com
      - EMAIL__SmtpServer=smtp.gmail.com
      - EMAIL__Port=465
      - EMAIL__Username=versity.identity.dev@gmail.com
      - EMAIL__Password=ebqatxmtxaurcdfu
      - EMAIL__ConfirmUrl=https://localhost:8001/api/auth/confirmemail/
      - ADMIN__Password=vers1ty.Admin
      - ADMIN__Email=versity.identity.dev@gmail.com
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/AppData/Roaming/Microsoft/UserSecrets/:/root/.microsoft/usersecrets:ro
    networks:
      - dev
  
  versity-apigateway-service:
    image: jejikeh/versity.apigateway:latest
    container_name: versity-apigateway-service
    depends_on:
      - versity-users-service
    ports:
      - 8000:80
      - 8001:443
    build:
      context: .
      dockerfile: src/Versity.ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=DEVELOPMENT
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=versity
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
      - JWT__Key=06AA645D-B70D-446F-90D7-192A5C1CAA6A
      - JWT__Issuer=https://versity.users:4001
      - JWT__Audience=https://versity.users:4001
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/AppData/Roaming/Microsoft/UserSecrets/:/root/.microsoft/usersecrets:ro
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  elasticsearch-data:
  postgres-data: