apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\jejik\scoop\apps\kompose\current\kompose.exe convert -f .\docker-compose.yml -o .\k8s\
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: versity-apigateway-service
  name: versity-apigateway-service
  namespace: default
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 443
  selector:
    io.kompose.service: versity-apigateway-service
status:
  loadBalancer: {}
