apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\jejik\scoop\apps\kompose\current\kompose.exe convert -f .\docker-compose.yml -o .\k8s\
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
  namespace: default
spec:
  ports:
    - name: "32181"
      port: 32181
      targetPort: 32181
  selector:
    io.kompose.service: zookeeper
status:
  loadBalancer: {}
