apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: token-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
    - hosts:
        - localhost
      secretName: identity-service-tls-secret
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: identity-service
                port:
                  number: 8080
