apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-deployment
  template:
    metadata:
      name: api-gateway-deployment
      labels:
        app: api-gateway-deployment
    spec:
      containers:
        - name: api-gateway-deployment
          image: jejikeh/versity.apigateway
          ports:
            - containerPort: 443
              name: https-web-api
            - containerPort: 80
              name: http-web-api
          env:
            - name: ASPNETCORE_URLS
              value: http://+80
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /weatherforecast
              port: 80
          readinessProbe:
            httpGet:
              path: /weatherforecast
              port: 80
      restartPolicy: Always