apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app.kubernetes.io/name: api-gateway
  ports:
    - protocol: TCP
      port: 7080
      targetPort: 80
  type: LoadBalancer