version: "3"

services: 
  versity.users:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=versity_users_dev
      - POSTGRES_USER=versity_dev
      - POSTGRES_PASSWORD=versity_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/db

volumes:
  postgres-data: