apiVersion: v1
kind: Service
metadata:
  name: products-kafka-service
spec:
  selector:
    app: products-kafka
    app.kubernetes.io/name: products-kafka
  ports:
    - protocol: TCP
      port: 9092
      nodePort: 31092
      targetPort: 9092
  type: NodePort