apiVersion: v1
kind: Service
metadata:
  name: products-zookeeper-service
spec:
  selector:
    app: products-zookeeper
    app.kubernetes.io/name: products-zookeeper
  ports:
    - protocol: TCP
      port: 2181
      nodePort: 30181
      targetPort: 2181
  type: NodePort