apiVersion: v1
kind: Service
metadata:
  name: products-redis-service
spec:
  selector:
    app: products-redis
    app.kubernetes.io/name: products-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP