apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-kafka-deployment
  labels:
    app: products-kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-kafka
  template:
    metadata:
      name: products-kafka
      labels:
        app: products-kafka
        app.kubernetes.io/name: products-kafka
    spec:
      hostname: products-kafka
      containers:
        - name: products-kafka
          image: confluentinc/cp-enterprise-kafka:latest
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: products-zookeeper-service:2181
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://products-kafka-service:9092
          ports:
            - containerPort: 9092