apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    app.kubernetes.io/name: products
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 80
  type: ClusterIP
  