# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Tests Identity Service

on:
  push:
    branches: [ "feature-cicd" ]
  pull_request:
    branches: [ "feature-cicd" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
      env:
        AdminId: ${{ secrets.TEST_ADMIN_ID }}
        AdminEmail: ${{ secrets.TEST_ADMIN_Email }}
        AdminPassword: ${{ secrets.TEST_ADMIN_Password }}
        JwtIssuer: ${{ secrets.TEST_JWT_ISSUER }}
        JWtAudience: ${{ secrets.TEST_JWT_AUDIENCE }}
        JwtKey: ${{ secrets.TEST_JWT_KEY }}
    
    - name: Setup UserSecrets
      shell: bash
      run: |
        dotnet user-secrets init --project ./src/Versity.Users/External/Presentation
        dotnet user-secrets set "Admin:Id" "$AdminId" --project ./src/Versity.Users/External/Presentation
        dotnet user-secrets set "Admin:Email" "$AdminEmail" --project ./src/Versity.Users/External/Presentation
        dotnet user-secrets set "Admin:Password" "$AdminPassword" --project ./src/Versity.Users/External/Presentation
        dotnet user-secrets set "Jwt:Issuer" "$JwtIssuer" --project ./src/Versity.Users/External/Presentation
        dotnet user-secrets set "Jwt:Audience" "$JwtAudience" --project ./src/Versity.Users/External/Presentation
        dotnet user-secrets set "Jwt:Key" "$JwtKey" --project ./src/Versity.Users/External/Presentation
        dotnet user-secrets set "Smtp:Password" "$JwtKey" --project ./src/Versity.Users/External/Presentation
          
    - name: Restore dependencies
      run: dotnet restore ./src/Versity.Users/External/Presentation/Presentation.csproj
      
    - name: Build
      run: dotnet build ./src/Versity.Users/External/Presentation/Presentation.csproj --no-restore
      
    - name: Test
      run: dotnet test ./src/Versity.Users/Tests/Users.Tests/Users.Tests.csproj --verbosity detailed

    - name: Publish
      run: dotnet publish ./src/Versity.Users/External/Presentation/Presentation.csproj --no-build
