# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Tests Products Service

on:
  push:
    branches: [ "feature-cicd" ]
  pull_request:
    branches: [ "feature-cicd" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./src/Versity.Products/External/Presentation/Presentation.csproj
      
    - name: Build
      run: dotnet build ./src/Versity.Products/External/Presentation/Presentation.csproj --no-restore
      
    - name: Test
      run: dotnet test ./src/Versity.Products/Tests/Products.Tests/Products.Tests.csproj --verbosity normal

    - name: Publish
      run: dotnet publish ./src/Versity.Products/External/Presentation/Presentation.csproj --no-build
